os:
  - linux
  - osx
language: generic
osx_image: xcode8
sudo: required
dist: trusty
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
env:
  - SWIFT_VERSION=3.1.0
script:
  - swift test
